/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class af_math_Matrix4 */

#ifndef _Included_af_math_Matrix4
#define _Included_af_math_Matrix4
#ifdef __cplusplus
extern "C" {
#endif
#undef af_math_Matrix4_M00
#define af_math_Matrix4_M00 0L
#undef af_math_Matrix4_M01
#define af_math_Matrix4_M01 4L
#undef af_math_Matrix4_M02
#define af_math_Matrix4_M02 8L
#undef af_math_Matrix4_M03
#define af_math_Matrix4_M03 12L
#undef af_math_Matrix4_M10
#define af_math_Matrix4_M10 1L
#undef af_math_Matrix4_M11
#define af_math_Matrix4_M11 5L
#undef af_math_Matrix4_M12
#define af_math_Matrix4_M12 9L
#undef af_math_Matrix4_M13
#define af_math_Matrix4_M13 13L
#undef af_math_Matrix4_M20
#define af_math_Matrix4_M20 2L
#undef af_math_Matrix4_M21
#define af_math_Matrix4_M21 6L
#undef af_math_Matrix4_M22
#define af_math_Matrix4_M22 10L
#undef af_math_Matrix4_M23
#define af_math_Matrix4_M23 14L
#undef af_math_Matrix4_M30
#define af_math_Matrix4_M30 3L
#undef af_math_Matrix4_M31
#define af_math_Matrix4_M31 7L
#undef af_math_Matrix4_M32
#define af_math_Matrix4_M32 11L
#undef af_math_Matrix4_M33
#define af_math_Matrix4_M33 15L
/*
 * Class:     af_math_Matrix4
 * Method:    mapvector
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_c2d_util_math_Matrix4_mapVector
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);
/*
 * Class:     af_math_Matrix4
 * Method:    multiply
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_c2d_util_math_Matrix4_multiply
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     af_math_Matrix4
 * Method:    inverse
 * Signature: ([F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_c2d_util_math_Matrix4_inverse
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     af_math_Matrix4
 * Method:    det
 * Signature: ([F)F
 */
JNIEXPORT jfloat JNICALL Java_c2d_util_math_Matrix4_det
  (JNIEnv *, jclass, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
